databases:
  - name: reporterapp
    databaseName: reporterapp_luwr
    user: reporterapp_luwr_user

services:
  - type: web
    name: ireporter
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: reporterapp_luwr
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false